# Generated by Django 6.0.4 on 2026-05-03 15:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Achievement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("organization", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("date", models.DateField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Hackathon", "Hackathon"),
                            ("Exam", "Exam"),
                            ("Event", "Event"),
                            ("Award", "Award"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "rank_or_result",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
            ],
            options={
                "verbose_name": "Achievement",
                "verbose_name_plural": "Achievements",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="Certification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("issuer", models.CharField(max_length=200)),
                ("issued_date", models.DateField()),
                ("credential_url", models.URLField(blank=True, null=True)),
                (
                    "badge_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="certifications/"
                    ),
                ),
            ],
            options={
                "verbose_name": "Certification",
                "verbose_name_plural": "Certifications",
                "ordering": ["-issued_date"],
            },
        ),
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("subject", models.CharField(max_length=200)),
                ("message", models.TextField()),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                ("is_read", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Contact Message",
                "verbose_name_plural": "Contact Messages",
                "ordering": ["-sent_at"],
            },
        ),
        migrations.CreateModel(
            name="Education",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("institution", models.CharField(max_length=200)),
                ("degree", models.CharField(max_length=200)),
                ("field", models.CharField(max_length=200)),
                ("start_year", models.IntegerField()),
                ("end_year", models.IntegerField(blank=True, null=True)),
                ("score", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "score_type",
                    models.CharField(
                        blank=True,
                        choices=[("CGPA", "CGPA"), ("Percentage", "Percentage")],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Education",
                "verbose_name_plural": "Educations",
                "ordering": ["-start_year"],
            },
        ),
        migrations.CreateModel(
            name="Experience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("role", models.CharField(max_length=200)),
                ("company", models.CharField(max_length=200)),
                (
                    "employment_type",
                    models.CharField(
                        help_text="e.g., Hybrid/Remote/Virtual Internship",
                        max_length=50,
                    ),
                ),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("is_current", models.BooleanField(default=False)),
                ("location", models.CharField(blank=True, max_length=200, null=True)),
                ("description", models.TextField()),
                ("tech_tags", models.CharField(max_length=255)),
                (
                    "company_logo",
                    models.ImageField(blank=True, null=True, upload_to="companies/"),
                ),
            ],
            options={
                "verbose_name": "Experience",
                "verbose_name_plural": "Experiences",
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "tagline",
                    models.CharField(
                        help_text='e.g. "GenAI Developer · CSE-AIML · Builder"',
                        max_length=255,
                    ),
                ),
                ("bio", models.TextField()),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "location",
                    models.CharField(default="Nellore, AP, India", max_length=200),
                ),
                ("github_url", models.URLField(blank=True, null=True)),
                ("linkedin_url", models.URLField(blank=True, null=True)),
                (
                    "resume",
                    models.FileField(blank=True, null=True, upload_to="resumes/"),
                ),
                (
                    "profile_photo",
                    models.ImageField(blank=True, null=True, upload_to="profile/"),
                ),
                (
                    "cgpa",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=4, null=True
                    ),
                ),
                ("university", models.CharField(blank=True, max_length=200, null=True)),
                ("degree", models.CharField(blank=True, max_length=200, null=True)),
                ("available_for_hire", models.BooleanField(default=True)),
                ("years_experience", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name": "Profile",
                "verbose_name_plural": "Profiles",
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(unique=True)),
                ("tagline", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "tech_stack",
                    models.CharField(
                        help_text="Comma-separated values", max_length=255
                    ),
                ),
                ("github_url", models.URLField(blank=True, null=True)),
                ("live_url", models.URLField(blank=True, null=True)),
                (
                    "thumbnail",
                    models.ImageField(blank=True, null=True, upload_to="projects/"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Completed", "Completed"),
                            ("Ongoing", "Ongoing"),
                            ("In Progress", "In Progress"),
                        ],
                        default="Completed",
                        max_length=50,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("GenAI", "GenAI"),
                            ("ML/DL", "ML/DL"),
                            ("Full Stack", "Full Stack"),
                            ("API", "API"),
                            ("Computer Vision", "Computer Vision"),
                            ("Other", "Other"),
                        ],
                        default="Full Stack",
                        max_length=50,
                    ),
                ),
                ("is_featured", models.BooleanField(default=False)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("order", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name": "Project",
                "verbose_name_plural": "Projects",
                "ordering": ["order", "-start_date"],
            },
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("GenAI/LLM", "GenAI/LLM"),
                            ("Machine Learning", "Machine Learning"),
                            ("Deep Learning", "Deep Learning"),
                            ("Backend", "Backend"),
                            ("Frontend", "Frontend"),
                            ("DevOps", "DevOps"),
                            ("Database", "Database"),
                            ("Tools", "Tools"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "proficiency",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(100),
                        ]
                    ),
                ),
                (
                    "icon_class",
                    models.CharField(
                        help_text='Font Awesome class string, e.g., "fa-brands fa-python"',
                        max_length=50,
                    ),
                ),
                (
                    "highlight",
                    models.BooleanField(
                        default=False, help_text="Show as featured skill badge in hero"
                    ),
                ),
                ("order", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name": "Skill",
                "verbose_name_plural": "Skills",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="TechStack",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("category", models.CharField(max_length=100)),
                (
                    "logo_url",
                    models.CharField(
                        help_text="External CDN logo URL or icon class", max_length=255
                    ),
                ),
                (
                    "color_hex",
                    models.CharField(
                        blank=True, help_text="e.g., #FFFFFF", max_length=7, null=True
                    ),
                ),
                ("order", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name": "Tech Stack Item",
                "verbose_name_plural": "Tech Stack Items",
                "ordering": ["order", "name"],
            },
        ),
    ]
