# Generated by Django 6.0.4 on 2026-05-05 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="logo",
            field=models.ImageField(blank=True, null=True, upload_to="profile/"),
        ),
    ]
